// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {internal} from '../models';

export function FetchClients():Promise<Array<string>>;

export function FetchMessages(arg1:string):Promise<Array<internal.Message>>;
