// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchClients() {
  return window['go']['main']['App']['FetchClients']();
}

export function FetchMessages(arg1) {
  return window['go']['main']['App']['FetchMessages'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SetIP(arg1) {
  return window['go']['main']['App']['SetIP'](arg1);
}
